import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { TopNav } from "@/components/navigation/TopNav";
import { ClerkProvider } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { ConnectedUserContext } from "@/hooks/context/connectedUserContext";
import { getUserByClerkId } from "@/actions/getUserByClerkId";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Holydevs - ",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
   // Utilisateur connecté
   const user = await currentUser();
   if (!user) return null;

   const dbUser = await getUserByClerkId(user.id);
   // if (!user) return null;

   return (
      <ClerkProvider>
         <html lang="fr" suppressHydrationWarning>
            <body className={cn("w-full min-h-screen", inter.className)}>
               {/* <ConnectedUserContext.Provider value={dbUser}> */}
               <TopNav />
               {/* </ConnectedUserContext.Provider> */}
               <main>{children}</main>
            </body>
         </html>
      </ClerkProvider>
   );
}
