import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { frFR } from "@clerk/localizations";
import { Toaster } from "@/components/shadcn/toaster";
import { ThemeProvider } from "@/components/provider/ThemeProvider";
import { auth } from "@clerk/nextjs/server";
import { getUserByClerkId } from "@/actions/getUserByClerkId";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Holydevs - ",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
   // Redirection vers l'onboarding si onboarding non complété
   const { userId } = auth();
   // Utilisateur dans la database
   const dbUser = await getUserByClerkId(userId ?? "");
   if (!dbUser?.firstname) {
      redirect("/onboarding");
   }

   return (
      <ClerkProvider localization={frFR}>
         <html lang="fr" suppressHydrationWarning>
            <body className={cn("w-full min-h-screen", inter.className)}>
               <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
               >
                  <Toaster />
                  <main>{children}</main>
               </ThemeProvider>
            </body>
         </html>
      </ClerkProvider>
   );
}
